# Practice data structures

We will create a data structure to hold our Germplasm data (I have updated it to be a little bit more complex... now a germplasm may hold TWO alleles - i.e. one germplasm has connections to more than one gene)

Represent these data in Python - create a **single variable** that contains all of this data (using lists and dictionaries).

Create loops over that data structure that can print the three tables to the screen.







<center>stock table</center>

germplasm_id |  amount  |  date  |  location  
 --- | --- | --- | --- 
 2 |  5  | 10/5/2013 |  Room 2234  
 1 | 9.8  | 12/1/2015 |  Room 998  


-----------------------------


<center>germplasm table</center>

id |  taxonid  |  alleles | genes 
 --- |--- | --- | ---
 1 |  4150  | def-1 | DEF
 2 | 3701  | ap3,  ag | AP3, AG
  
--------------------------------

<center>gene table</center>

  gene  |  gene_name  |  embl
 --- | ---  | --- 
  DEF  | Deficiens  | https://www.ebi.ac.uk/ena/data/view/AB516402
  AP3  | Apetala3   |   https://www.ebi.ac.uk/ena/data/view/AF056541
  AG  | Agamous   |   https://www.ebi.ac.uk/ena/data/view/AL161549
  

In [17]:
# put your code here... take it one step at a time!
# do just one table (an easy one, like the gene table)
DEF ={'gene': 'DEF', 'name': 'Deficiens', 'embl':'http://AB123434'}
AP3 ={'gene': 'AP3', 'name': 'Apetala3', 'embl':'http://AF056541'}
AG ={'gene': 'AG', 'name': 'Agamous', 'embl':'http://AL161549'}

gene_table = [DEF, AP3, AG]

print ("gene\tgene_name\tembl")
for gene in gene_table:
    #print(gene['gene'], "\t", gene['name'], '\t', gene['embl']) #problema: añadimos extra spaces- está mal
    #print("%s\t%s\t%s" % (gene['gene'], gene['name'], gene['embl'])) #en este caso % al final se usa como separador lenguaje C
    print("{0}\t{1}\t{2}".format(gene['gene'], gene['name'], gene['embl'])) #Es el más usado en Phyton

# create the data structure and print it
#Stock table 
Stock1= {'germplasm_id': 2, 'amount': 5, 'date':'10/5/2013', 'location': 'Room 2234'}
Stock2= {'germplasm_id': 1, 'amount': 9.8, 'date':'12/1/2015', 'location': 'Room 998'}

stocks = [Stock1, Stock2]

print("") #estudiar por qué es necesario - lo usamos para crear un espacio
print("germplasm_id\tamount\tdate\tlocation")
for stock in stocks:
    print("%d\t%f\t%s\t%s" % (stock['germplasm_id'], stock['amount'], stock['date'], stock['location']))
    
# then pick a harder table (like germplasm), create the data structure, and print it #one has two items

#Una solución
Germplasm1= {'id': 1, 'taxonid': 4150, 'alleles': ['def-1'], 'genes': ['DEF']}
Germplasm2= {'id': 2, 'taxonid': 3701, 'alleles': ['ap3', 'ag'], 'genes': ['AP3', 'AG']}

germplasm_table1 = [Germplasm1, Germplasm2]

print("")
print("")
print("id\ttaxonid\t\talleles\tgenes")
for germplasm in germplasm_table1:
    alleles = germplasm['alleles']
    genes = germplasm['genes']
    allelestring = ""
    for allele in alleles:
        allelestring += allele + ","
    genestring = ""
    for gene in genes:
        genestring += gene + ","
    print("%d\t%d\t%s\t%s" % (germplasm['id'], germplasm['taxonid'], germplasm['alleles'], germplasm['genes'] ))
    
#Otra solución solución sería definir la segunda línea dos veces, creando una línea nueva con el mismo id pero donde se separen 
#los items. ES mejor porque mantiene los genes alineados, PREGUNTAR CUÁL ERA LA RAZÓN
#Hay otro problema, y es que no podemos tener en una database el mismo id, habría que crear otra columna que los 
#identique de igual forma. En este caso normalizamos los datos
Germplasm1= {'id': 1, 'taxonid': 4150, 'alleles': 'def-1', 'genes': DEF}
Germplasm3= {'id': 2, 'taxonid': 3701, 'alleles': 'ap3', 'genes': AP3}
Germplasm4= {'id': 2, 'taxonid': 3701, 'alleles': 'ag', 'genes': AG}

print(Germplasm1['genes']['embl'] + "IT IS HERE")

print("")
print("")
germs = [Germplasm1, Germplasm3, Germplasm4]

for thisgerm in germs:
    website = thisgerm['genes']['embl']
    print ("the website for the gene of allele %s is %s" % (thisgerm['alleles'], website))
#create an iterator that creates a "thisgerm" for each Germplasm:
website = thisgerm['genes']['embl'] #create website with the germplasm subject 
#Website is in the gene definition
#They have in common de gene definition, but the genes are letters, so we change the variable 'DEF' to DEF, which 
#contains the direct objects defined at the beggining with the first table
#print "the website for the gene of allele {allele} is {website}
# finally, create the entire database, where all three tables are joined together

gene	gene_name	embl
DEF	Deficiens	http://AB123434
AP3	Apetala3	http://AF056541
AG	Agamous	http://AL161549

germplasm_id	amount	date	location
2	5.000000	10/5/2013	Room 2234
1	9.800000	12/1/2015	Room 998


id	taxonid		alleles	genes
1	4150	['def-1']	['DEF']
2	3701	['ap3', 'ag']	['AP3', 'AG']
http://AB123434IT IS HERE


the website for the gene of allele def-1 is http://AB123434
the website for the gene of allele ap3 is http://AF056541
the website for the gene of allele ag is http://AL161549


 <pre>  </pre>

<span style="visibility:hidden;">
DEF = {'id': 'DEF', 'name': 'Deficiens', 'embl': 'http://AB123434'}
AP3 = {'id': 'AP3', 'name': 'Apetala3', 'embl': 'http://AB123434'}
AG = {'id': 'AG', 'name': 'Agamous', 'embl': 'http://AB123434'}
gp1 = {'id': 1, 'taxon': 4150, 'alleles': ['def1'], 'genes': [DEF]}
gp2 = {'id': 2, 'taxon': 4150, 'alleles': ['ap3', 'ag'], 'genes': [AP3, AG]}
stock1 = {'germplasm': gp2, 'amount': 5, 'date': '10/5/2013', 'location': 'Room 2234' }
stock2 = {'germplasm': gp1, 'amount': 9.8, 'date': '12/1/2015', 'location': 'Room 998' }
database = [stock1, stock2]
for stock in database:
    print(stock['germplasm']['id'], ", ", stock['amount'],",",stock['date'],",",stock['location'])
</span>